### ISSUE TITLE
What is the difference to Nextcloud's official project?

### ISSUE THREAD

**Issue by rugk** [undo-ransomware/ransomware_detection#34]
What is the difference to https://github.com/nextcloud/ransomware_protection and why should I use yours instead of the other one?

Also, I'd highly urge you to make that answer/difference clear in the Readme and other descriptions in the Nextcloud store, because they serve very similar needs, likely should not be combined (or can they?? would that make sense?), so users have to choose/decide for one *and* even have **very** similar names.

All that combined, this can lead to a lot of confusion, so IMHO you need to make that super clear and differentiate the projects.

**Comment by ilovemilk** [comment]
The main difference between the official Nextcloud project and this project is that the official projects relies on blacklisting of file malicious file extensions therefore only detects known ransomware files. This project tries to also detect unknown ransomware by analysing the files for generic ransomware detection patterns like e.g.: read/write patterns, file entropy, etc.

This is a very good point. They can be used both combined: Ransomware protection should catch all known ransomware and this project tries to catch all unknown ransomware.

Thanks for the hint I will try to clarify these points in the readme to hopefully remove the confusion. So that the users can profit the most from both apps.

**Comment by haarp** [comment]
Wouldn't it be even better if you worked with the official app and combined your efforts, if possible?

**Comment by ilovemilk** [comment]
I added a FAQ section to the [README](https://github.com/undo-ransomware/ransomware_detection/blob/feature/rework-ui/README.md). Do you think this clarifies this topic?

**Comment by rugk** [comment]
Yeah, as for the Readme this is all nice and explains it well…

However, in the [Nextcloud app store](https://apps.nextcloud.com/apps/ransomware_protection) there is still no indication. At least be some minor indication would be useful there, I guess…

**Comment by ilovemilk** [comment]
Thanks I totally forgot about that!

**Comment by ilovemilk** [comment]
I just uploaded a new version to Appstore with an updated info. I hope this helps! :)
