### ISSUE TITLE
Replace defective version 0.9.0 by 0.9.1=0.8?

### ISSUE THREAD

**Issue by sm8ps** [undo-ransomware/ransomware_detection#55]
By accident I came to read your warning against using version 0.9.0. I went to check on my NC-instance and found out that I had already updated to that version as was suggested by the updater. I have deactivated since so this is my work-around.

However, I wonder what could have happened if I had not spotted this announcement by chance. Would it be a good idea to retract version 0.9.0 by replacing it by a "phony" version 0.9.1 which would in essence simply be the previous one from the 0.8 version? This way, version 0.9.0 could be removed from servers that had it installed semi-automatically by the very same procedure.

**Comment by sm8ps** [comment]
After studying the warning more carefully, I would rather have re-phrased the title of this issue to "Replace *unsafe* version (...)". Sorry if it should sound offensive which is not at all my intention.

**Comment by ilovemilk** [comment]
No it's not offensive at all. As this issue arise I thought what could I do to notify all the users because Nextcloud doesn't offer a way to do so. So I decided to delete the version 0.9.0 from the Appstore and add a warning to the repository.

>"Replace unsafe version (...)"
That's a very good idea I will do this but I will also add a recommendation to disable the app until this is resolved.

> Would it be a good idea to retract version 0.9.0 by replacing it by a "phony" version 0.9.1 which would in essence simply be the previous one from the 0.8 version?

Would be a good possibility. I try to reproduce and solve this issue this evening if I'm not able to do so I will replace 0.9.0 with a 0.9.1 which is the old version 0.8.0.

**Comment by ilovemilk** [comment]
I removed the app completely and replaced it with a dummy app with warnings to disable or remove the app.

**Comment by sm8ps** [comment]
Uh, that sounds really bad. Good luck with finding a solution! Sorry that I am not of any help when it comes to the actual code. However, I am sure that many people find this app an extremely valuable extension to Nextcloud.

**Comment by ilovemilk** [comment]
It was necessary as I dont want to harm any data. Sadly, it's not possible to disable the app for all users via the app store. I hope with this I can reach all the users.
